### ISSUE TITLE
Port 80 does not work with http2

### ISSUE THREAD

**Issue by soerface** [hispanico/ansible-nginx-revproxy#12]
https://github.com/hispanico/ansible-nginx-revproxy/blob/b276e0767b54ff4aabea74a654f59e69287e092d/templates/reverseproxy.conf.j2#L8

The default port for unencrypted connections (80) should not use http2, since the browser will not know what to do with the answer, resulting in the download of a binary file.

Analogous, the default port in the ssl templates should be 443 instead of 80:

https://github.com/hispanico/ansible-nginx-revproxy/blob/b276e0767b54ff4aabea74a654f59e69287e092d/templates/reverseproxy_ssl.conf.j2#L8

https://github.com/hispanico/ansible-nginx-revproxy/blob/b276e0767b54ff4aabea74a654f59e69287e092d/templates/reverseproxy_ssl_letsencrypt.conf.j2#L13

**Comment by empi89** [comment]
This seems also to be an issue with the letsencrypt functionality. Can you make http2 optional?

**Comment by hispanico** [comment]
I've just set http2 only on ssl vhosts.
#13
