### ISSUE TITLE
hispanico.nginx-revproxy was not found on https://galaxy.ansible.com/api/.

### ISSUE THREAD

**Issue by PavelPikat** [hispanico/ansible-nginx-revproxy#45]
Cannot install the role anymore. Was it delisted from Ansible Galaxy?

**Comment by hispanico** [comment]
The role has been renamed to [hispanico.nginx_revproxy](https://galaxy.ansible.com/hispanico/nginx_revproxy).

[Ansible Galaxy Docs](https://galaxy.ansible.com/docs/contributing/importing.html#importing-roles):
"Starting in v3.0, Galaxy no longer perform this calculation. Instead, the default role name is the unaltered repository name, with a couple minor exceptions, including: converting the name to all lowercase, and replacing any ‘-‘ or ‘.’ characters with ‘_’."
